rockgol/urls.py
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.conf.urls import patterns, include, url
from apps.core.views import TorneioDetailView, TreinoDetailView, ExibicaoListView, TimeDetailView, \
    SegundaEtapaDetailView, CampeonatoFinaisListView

from apps.website.views import HomePageView, NoticiasView, ParceirosView, ApoioView, AtracoesView, OrganizacaoView, \
    NoticiaDetailView, GaleriaListView
from rockgol import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^manage-cms/', include(admin.site.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^torneios/(?P<campeonato_slug>[\w_-]+)/$', TorneioDetailView.as_view(), name='torneio_listagem'),
    url(r'^torneios/(?P<campeonato_slug>[\w_-]+)/segunda-etapa/$', SegundaEtapaDetailView.as_view(), name='segunda_etapa_listagem'),
    url(r'^torneios/(?P<campeonato_slug>[\w_-]+)/(?P<time_slug>[\w_-]+)-(?P<id>\d+).html', TimeDetailView.as_view(), name='time_detalhe'),
    url(r'^exibicoes/$', ExibicaoListView.as_view(), name='modalidades'),
    url(r'^fase-final/$', CampeonatoFinaisListView.as_view(), name='fase_final_listagem'),
    url(r'^exibicoes/(?P<slug>[\w_-]+)-(?P<id>\d+).html', TreinoDetailView.as_view(), name='treino-detalhe'),
    url(r'^noticias/$', NoticiasView.as_view(), name='noticias'),
    url(r'^noticias/(?P<slug>[\w_-]+)-(?P<id>\d+).html', NoticiaDetailView.as_view(), name='noticia-detalhe'),
    url(r'^galerias/$', GaleriaListView.as_view(), name='galerias'),
    url(r'^atracoes/$', AtracoesView.as_view(), name='atracoes'),
    url(r'^organizacao/$', OrganizacaoView.as_view(), name='organizacao'),
    url(r'^parceiros/$', ParceirosView.as_view(), name='parceiros'),
    url(r'^apoio/(?P<slug>[\w_-]+)-(?P<id>\d+).html', ApoioView.as_view(), name='parceiro-interna'),
    (r'^albuns/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'apps.multimidia.views.album'),
    url(r'^contato/$', 'apps.website.views.contato', name='contato'),
    url(r'^minha-conta/$', 'apps.core.views.minha_conta', name='minha-conta'),
    url(r'login/$', 'apps.core.views.login', name='login'),
    url(r'^sair/$', 'apps.core.views.sair', name='sair'),
    url(r'sorteio/$', 'apps.core.views.sorteio', name='sorteio'),

)

apps/core/models.py
# -*- coding: utf-8 -*-
import datetime
from django.contrib import auth
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, Permission, \
    _user_get_all_permissions, _user_has_perm, _user_has_module_perms, Group
from django.db import models
from django.db.models.signals import post_save
from django.shortcuts import redirect
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
from django.db.models import signals, Q
from django.template.defaultfilters import slugify

TIPO_USUARIO = (('1', 'Usuário Sistema'),
                ('2', 'Representante Futebol Masculino'),
                ('3', 'Representante Futebol Feminino'),
                ('4', 'Representante Vôlei'))


class UsuarioManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Usuários devem ter um endereço de email.')

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password=password, )
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Usuario(AbstractBaseUser):
    email = models.EmailField(verbose_name='Email', max_length=255, unique=True, db_index=True, )
    telefone = models.CharField(max_length=15)
    nome = models.CharField(max_length=200, null=True, blank=True)
    endereco = models.CharField('Endereço', max_length=200, null=True, blank=True)
    dt_nasc = models.DateField('Data de Nascimento', null=True, blank=True)
    cpf = models.CharField(max_length=15)
    rg = models.CharField(max_length=15)
    is_active = models.BooleanField('Ativo?', default=True)
    is_superuser = models.BooleanField('Administrador?', default=False)
    is_staff = models.BooleanField(('Acesso ao Manage?'), default=False)
    user_permissions = models.ManyToManyField(Permission, verbose_name=('Permissões'), blank=True)
    groups = models.ManyToManyField(Group, verbose_name=('groups'), blank=True)
    tipo=models.CharField('Tipo', max_length=1, choices=TIPO_USUARIO, default='1')


    objects = UsuarioManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    def get_group_permissions(self, obj=None):
        """
        Returns a list of permission strings that this user has through his/her
        groups. This method queries all available auth backends. If an object
        is passed in, only permissions matching this object are returned.
        """
        permissions = set()
        for backend in auth.get_backends():
            if hasattr(backend, "get_group_permissions"):
                if obj is not None:
                    permissions.update(backend.get_group_permissions(self,
                                                                     obj))
                else:
                    permissions.update(backend.get_group_permissions(self))
        return permissions

    def get_all_permissions(self, obj=None):
        return _user_get_all_permissions(self, obj)

    def has_perm(self, perm, obj=None):
        """
        Returns True if the user has the specified permission. This method
        queries all available auth backends, but returns immediately if any
        backend returns True. Thus, a user who has permission from a single
        auth backend is assumed to have permission in general. If an object is
        provided, permissions for this specific object are checked.
        """

        # Active superusers have all permissions.
        if self.is_active and self.is_superuser:
            return True

        # Otherwise we need to check the backends.
        return _user_has_perm(self, perm, obj)

    def has_perms(self, perm_list, obj=None):
        """
        Returns True if the user has each of the specified permissions. If
        object is passed, it checks if the user has all required perms for this
        object.
        """
        for perm in perm_list:
            if not self.has_perm(perm, obj):
                return False
        return True

    def has_module_perms(self, app_label):
        """
        Returns True if the user has any permissions in the given app label.
        Uses pretty much the same logic as has_perm, above.
        """
        # Active superusers have all permissions.
        if self.is_active and self.is_superuser:
            return True

        return _user_has_module_perms(self, app_label)


class Treino(models.Model):
    status = models.BooleanField(default=True)
    nome = models.CharField(max_length=150)
    slug = models.SlugField(max_length=100, blank=True)
    texto = models.TextField('Descrição')
    imagem = ThumbnailerImageField(upload_to='uploads/modalidades/%Y/%m')
    imagem_cortada = ImageRatioField('imagem', '270x150')
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.nome

    def get_imagem_cortada(self):
        return get_thumbnailer(self.imagem).get_thumbnail({
                    'size': (270,150),
                    'box': self.imagem_cortada,
                    'crop': True,
                    'detail': True,
                }).url

    @models.permalink
    def get_absolute_url(self):
        return 'treino-detalhe', [self.slug, self.pk]

    class Meta:
        verbose_name_plural = "Exibições"


def treino_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    artigo com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    if not instance.slug:
        slug = slugify(instance.nome)
        novo_slug = slug
        contador = 0

        while Treino.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug
signals.pre_save.connect(treino_pre_save, sender=Treino)

CATEGORIA_CHOICES = (('1', 'Masculino'), ('2', 'Feminino'))
TIPO_CHOICES = (('1', 'Futebol'), ('2', 'Volei'))

class Time(models.Model):
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES)
    genero = models.CharField(max_length=2, choices=CATEGORIA_CHOICES)
    status = models.BooleanField(default=True)
    nome = models.CharField(max_length=150)
    time_slug = models.SlugField(max_length=100, blank=True)
    sigla = models.CharField(max_length=2)
    campeonato = models.ForeignKey('Campeonato')
    responsavel = models.ForeignKey(Usuario)
    cor_uniforme = models.CharField(max_length=20, null=True, blank=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.nome

    @models.permalink
    def get_absolute_url(self):
        return 'time_detalhe', [self.campeonato.campeonato_slug, self.time_slug, self.pk]

class Jogador(models.Model):
    status = models.BooleanField(default=True)
    time = models.ForeignKey(Time)
    nome = models.CharField(max_length=150)
    data_nascimento = models.DateField()
    rg = models.CharField(max_length=15)
    cpf = models.CharField(max_length=15, unique=True)
    telefone = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField()
    imagem = ThumbnailerImageField(upload_to='uploads/jogador/%Y/%m')
    imagem_cortada = ImageRatioField('imagem', '160x160')
    twitter = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    instrumento = models.CharField(max_length=70, blank=True, null=True)
    nome_banda = models.CharField("Nome da Banda",max_length=150, blank=True, null=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def get_imagem_cortada(self):
        return get_thumbnailer(self.imagem).get_thumbnail({
                    'size': (160,160),
                    'box': self.imagem_cortada,
                    'crop': True,
                    'detail': True,
                }).url

    def get_idade(self):
        from datetime import date
        return (date.today() - self.data_nascimento).days / 365

    class Meta:
        verbose_name_plural = 'Jogadores'

    def __unicode__(self):
            return self.nome


class Campeonato(models.Model):
    status = models.BooleanField(default=True)
    imagem_home = ThumbnailerImageField(upload_to='uploads/campeonato/%Y/%m', blank=True, null=True)
    imagem_interna = ThumbnailerImageField(upload_to='uploads/campeonato/%Y/%m', blank=True, null=True)
    imagem_home_cortada = ImageRatioField('imagem_home', '270x150')
    imagem_interna_cortada = ImageRatioField('imagem_interna', '425x172')
    nome = models.CharField("Nome do Campeonato", max_length=100)
    campeonato_slug = models.SlugField(max_length=100, blank=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.nome

    def get_imagem_cortada(self):
        return get_thumbnailer(self.imagem_home).get_thumbnail({
                    'size': (270,150),
                    'box': self.imagem_home_cortada,
                    'crop': True,
                    'detail': True,
                }).url

    def get_imagem_listagem(self):
        return get_thumbnailer(self.imagem_interna).get_thumbnail({
                    'size': (425,172),
                    'box': self.imagem_interna_cortada,
                    'crop': True,
                    'detail': True,
                }).url

    @models.permalink
    def get_absolute_url(self):

apps/website/forms.py
from django import forms
from django.core.mail import send_mail

class FormContato(forms.Form):
    nome = forms.CharField(max_length=50)
    email = forms.EmailField()
    mensagem = forms.Field(widget=forms.Textarea)

    def enviar(self):
        titulo = 'Mensagem enviada pelo site'
        destino = 'email@gmail.com'
        texto = """
        Nome: %(nome)s
        E-mail: %(email)s
        Mensagem: %(mensagem)s
        """ % self.cleaned_data

        send_mail(
            subject=titulo,
            message=texto,
            from_email=destino,
            recipient_list=[destino],
            )

apps/website/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.shortcuts import redirect, render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView, ListView, DetailView
from apps.core.models import Campeonato, Treino, Tabela
from apps.multimidia.models import Banner, Album
from apps.website.forms import FormContato
from apps.website.models import Noticia, Apoio, Atracao, Organizacao


class HomePageView(TemplateView):
    template_name = 'website/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['campeonato'] = Campeonato.objects.filter(status=True).order_by('nome')
        context['noticias'] = Noticia.objects.filter(status=True)[:3]
        context['treinos'] = Treino.objects.filter(status=True).order_by('?')[:4]
        context['tabelas_jogos_masculino_grupo_a'] = Tabela.objects.filter(grupo='1', genero='1').distinct().order_by('pontos')
        context['tabelas_jogos_masculino_grupo_b'] = Tabela.objects.filter(grupo='2', genero='1').distinct().order_by('pontos')
        context['tabelas_jogos_masculino_grupo_c'] = Tabela.objects.filter(grupo='3', genero='1').distinct().order_by('pontos')
        context['tabelas_jogos_masculino_grupo_d'] = Tabela.objects.filter(grupo='4', genero='1').distinct().order_by('pontos')

        context['tabelas_jogos_feminino_grupo_a'] = Tabela.objects.filter(grupo='1', genero='2').distinct().order_by('pontos')
        context['tabelas_jogos_feminino_grupo_b'] = Tabela.objects.filter(grupo='2', genero='2').distinct().order_by('pontos')
        context['tabelas_jogos_feminino_grupo_c'] = Tabela.objects.filter(grupo='3', genero='2').distinct().order_by('pontos')
        context['tabelas_jogos_feminino_grupo_d'] = Tabela.objects.filter(grupo='4', genero='2').distinct().order_by('pontos')

        try:
            context['banner_medio'] = Banner.objects.filter(status=True, publicado_em__lte=datetime.now(), remover_em__gte=datetime.now())[0]
            context['album'] = Album.objects.filter(status=True)[0]
        except:
            return context
        return context


class NoticiasView(ListView):
    template_name = 'website/noticias.html'
    model = Noticia
    paginate_by = 8

    def get_queryset(self):
        return self.model.objects.filter(status=True).order_by('-data_criacao')

class GaleriaListView(ListView):
    template_name = 'website/listagem-galeria.html'
    model = Album

    def get_queryset(self):
        return self.model.objects.filter(status=True).order_by('-cadastrado_em')

class NoticiaDetailView(DetailView):
    model = Noticia
    template_name = 'website/noticia.html'

class AtracoesView(ListView):
    template_name = 'website/atracoes.html'
    model = Atracao

    def get_queryset(self):
        return self.model.objects.filter(status=True).order_by('-data_criacao')


class OrganizacaoView(ListView):
    template_name = 'website/organizacao.html'
    model = Organizacao


class ParceirosView(ListView):
    template_name = 'website/parceiros.html'
    model = Apoio

    def get_queryset(self):
        return self.model.objects.filter(status=True).order_by('posicao')


class ApoioView(DetailView):
    model = Apoio
    template_name = 'website/parceiros-interna.html'

def contato(request):
    if request.method == 'POST':
        form = FormContato(request.POST)
        if form.is_valid():
            form.enviar()
            mostrar = 'Mensagem enviada!'
            form = FormContato()
            return redirect('/')
    else:
        form = FormContato()

    return render_to_response('website/contatos.html', locals(), context_instance=RequestContext(request))

templates/website/galeria-interna.html
{% extends 'componentes/base.html' %}
{% block content %}
<section class="mb">
    <div class="row">
        <div class="large-9 medium-9 small-12 columns">

            <section class="times mb">
                <div class="titulo-block">
                    <a href="{% url 'galerias' %}">
                        <h2 class="titulo-block">Galeria de fotos</h2>
                    </a>
                    <div></div>
                </div>
                <h4 class="title-categ">{{ album.titulo }}</h4>
                <ul class="list-fotos clearing-thumbs small-block-grid-3 medium-block-grid-5 large-block-grid-6" data-clearing>
                  {% for foto in album.fotos.all %}
                  <li><a href="{{ MEDIA_URL }}{{ foto.foto }}"><img data-caption="{{ foto.legenda }}" src="{{ foto.get_thumb }}"></a></li>
                  {% endfor %}
                </ul>


                <div class="row">
                        <div class="large-12 medium-12 columns">

                            <div class="titulo-block">
                                <a href="">
                                    <h2 class="titulo-block">comente</h2>
                                </a>

                                <div></div>
                            </div>
                            <div class="comentarios mobile-off">
                                <div class="fb-comments" data-href="www.rockgol.com.br{{ request.path }}" data-width="870" data-numposts="5" data-colorscheme="light"></div>
                            </div>
                        </div>
                    </div>
            </section>

        </div>
        {% include 'componentes/sidebar.html' %}
    </div>
</section>
    <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script>
{% endblock %}

templates/website/listagem-galeria.html
{% extends 'componentes/base.html' %}

{% block content %}
    <section class="mb">
        <div class="row">
        <div class="large-9 medium-9 small-12 columns">
        <section class="galeria">
            <div class="row">
                <div class="large-12 medium-12 small-12 columns">
                    <div class="titulo-block">
                            <h2 class="titulo-block">galeria de fotos</h2>

                        <div></div>
                    </div>
                    <ul class="small-block-grid-1 medium-block-grid-1 large-block-grid-1">
                        {% for album in object_list %}
                        <li>
                            <div class="item-galeria">
                                <a href="{{ album.get_absolute_url }}">
                                    <img src="{{ album.get_big }}" alt="{{ album.titulo }}">

                                    <div class="titulo-album">
                                        <p>{{ album.titulo }}</p>
                                    </div>
                                </a>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </section>
    </div>

    {% include 'componentes/sidebar.html' %}
    </div>
    </section>

{% endblock %}

templates/website/modalidades-finais.html
{% extends 'componentes/base.html' %}
{% block content %}
    <section class="mb">
        <div class="row">
            <div class="large-9 medium-9 small-12 columns">

                <section class="contato mb">
                    <div class="titulo-block">
                        <a href="">
                            <h2 class="titulo-block">Modalidades</h2>
                        </a>

                        <div></div>
                    </div>

                    <div class="box-bottom">
                        <h4 class="title-categ">Torneios</h4>
                        <ul class="list-block small-block-grid-2 medium-block-grid-2 large-block-grid-2">
                            {% for campeonato in object_list %}
                            <li>
                                <a href="{% url "segunda_etapa_listagem" campeonato.campeonato_slug %}"><img src="{{ campeonato.get_imagem_listagem }}" alt="{{ campeonato.nome }}"></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </section>

            </div>

            {% include 'componentes/sidebar.html' %}

        </div>

    </section>
{% endblock %}

templates/website/modalidades.html
{% extends 'componentes/base.html' %}
{% block content %}
    <section class="mb">
        <div class="row">
            <div class="large-9 medium-9 small-12 columns">

                <section class="contato mb">
                    <div class="titulo-block">
                        <a href="">
                            <h2 class="titulo-block">Modalidades</h2>
                        </a>

                        <div></div>
                    </div>

                    <div class="box-bottom">
                        <h4 class="title-categ">Torneios</h4>
                        <ul class="list-block small-block-grid-2 medium-block-grid-2 large-block-grid-2">
                            {% for campeonato in campeonatos %}
                            <li>
                                <a href="{{ campeonato.get_absolute_url }}"><img src="{{ campeonato.get_imagem_listagem }}" alt="{{ campeonato.nome }}"></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="box-bottom">
                        <h4 class="title-categ">Treinos e Exposições</h4>
                        <ul class="list-block small-block-grid-2 medium-block-grid-3 large-block-grid-3">
                            {% for treino in object_list %}
                            <li>
                                <a href="{{ treino.get_absolute_url }}"><img src="{{ treino.get_imagem_cortada }}" alt="{{ treino.nome }}"></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </section>

            </div>

            {% include 'componentes/sidebar.html' %}

        </div>

    </section>
{% endblock %}

templates/website/parceiros-interna.html
{% extends 'componentes/base.html' %}
{% block content %}
<section class="mb">
    <div class="row">
        <div class="large-12 medium-12 small-12 columns">
            <section class="times mb">
                <div class="titulo-block">
                    <a href="{% url 'parceiros' %}">
                        <h2 class="titulo-block">Nossos parceiros</h2>
                    </a>
                    <div></div>
                </div>
                <h4 class="title-categ">{{ object.titulo }}</h4>
                <div class="row">
                    <div class="large-4 medium-4 small-12 columns">
                        <div class="logo-parceiro text-center">
                            <img src="{{ object.get_imagem_interna }}" alt="{{ object.titulo }}">
                        </div>
                    </div>
                    <div class="large-8 medium-8 small-12 columns">
                        <div class="info-parceiro">
                            <p>{{ object.descricao }}</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section>
{% endblock %}

templates/website/time.html
{% extends 'componentes/base.html' %}
{% block content %}
    <section class="mb">
    <div class="row">
    <div class="large-9 medium-9 small-12 columns">

    <section class="times mb">
    <div class="titulo-block">
        <a href="">
            <h2 class="titulo-block">Escalação dos times</h2>
        </a>
    </div>
    <h4 class="title-categ">{{ object.nome }}</h4>
    <ul class="small-block-grid-2 medium-block-grid-5 large-block-grid-5">
        {% for jogador in object.jogador_set.all %}
        <li>
            <div class="item-play">
                <div class="img-play">
                    <img src="{{ jogador.get_imagem_cortada }}" alt="">
                </div>
                <div class="info-play">
                    <h4>{{ jogador.nome|truncatewords:"2" }}</h4>

                    <p>Idade:{{ jogador.get_idade }} Anos</p>
                    <ul class="social-top">
                        <li>
                            {% if jogador.facebook %}
                            <a href="{{ jogador.facebook }}"><i class="fi-social-facebook"></i></a>
                            {% else %}
                            <a href="https://www.facebook.com/CurtaRockGolTeresina"><i class="fi-social-facebook"></i></a>
                            {% endif %}
                        </li>
                        <li>
                            {% if jogador.twitter %}
                            <a href="{{ jogador.twitter }}"><i class="fi-social-twitter"></i></a>
                            {% else %}
                            <a href="https://twitter.com/RockGolTeresina"><i class="fi-social-twitter"></i></a>
                            {% endif %}
                        </li>
                        <li>
                            {% if jogador.instagram %}
                            <a href="{{ jogador.instagram }}"><i class="fi-social-instagram"></i></a>
                            {% else %}
                            <a href="http://instagram.com/rockgolteresina"><i class="fi-social-instagram"></i></a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    </section>

    <section class="tabela mb">
        <div class="titulo-block">
            <a href="">
                <h2 class="titulo-block">pontuação</h2>
            </a>

            <div></div>
        </div>
        <div class="row">
            <div class="large-12 medium-12 small-12 columns">
                <h4 class="title-categ">{{ time_tabela.get_grupo_display }}</h4>
                <div class="pontuacao">
                    <table>
                        <thead>
                            <tr>
                                <th width="200">Equipe</th>
                                <th width="20">J</th>
                                <th width="20">V</th>
                                <th width="20">E</th>
                                <th width="20">D</th>
                                <th width="20">GP</th>
                                <th width="20">GC</th>
                                <th width="20">Pts</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for time in todos_times_tabela %}
                            <tr>
                                <td>
                                    <a href="{{ time.time.get_absolute_url }}"><div>
                                        <div class="escudo">
                                            <h5>{{ time.time.sigla }}</h5>
                                        </div>
                                        <p class="nome-time">{{ time.time.nome }}</p>
                                    </div></a>
                                </td>
                                <td>{{ time.jogos }}</td>
                                <td>{{ time.vitorias }}</td>
                                <td>{{ time.empates }}</td>
                                <td>{{ time.derrotas }}</td>
                                <td>{{ time.gols_pro }}</td>
                                <td>{{ time.gols_contra }}</td>
                                <td>{{ time.pontos }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
                        <div class="large-12 medium-12 columns">

                            <div class="titulo-block">
                                <a href="">
                                    <h2 class="titulo-block">comente</h2>
                                </a>

                                <div></div>
                            </div>
                            <div class="comentarios mobile-off">
                                <div class="fb-comments" data-href="www.rockgol.com.br{{ request.path }}" data-width="870" data-numposts="5" data-colorscheme="light"></div>
                            </div>
                        </div>
                    </div>
    </section>

    </div>

    {% include 'componentes/sidebar.html' %}
    </div>
    </section>
     <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script>
{% endblock %}